### ISSUE TITLE
error "NullPointerException"

### ISSUE THREAD

**Issue by ghost** [SuperiozDE/CastleRush#1]
logs
http://hastebin.com/ifafoqajeh.avrasm

**Comment by Superioz** [comment]
Could you please try to re-download the plugin? If it's still broken, I'll look for a solution

**Comment by ghost** [comment]
new logs
http://hastebin.com/oyupafumuj.avrasm

**Comment by ghost** [comment]
PaperSpigot
https://tcpr.ca/downloads/paperspigot

**Comment by Superioz** [comment]
Okay, I found the bug. I'll fix it and update the resource asap
